#!/usr/bin/env node

var fs = require('fs');

var ephemeris = require("./lib/ephemeris_jpl")
var convert = require("./lib/convert");
var lua = require("./lib/lua");

for (var object_name in ephemeris.objects) {
    if (ephemeris.objects.hasOwnProperty(object_name)) {

        ephemeris.get(object_name, "2014-05-13", function(err, object){
            if (object.ephemeris) {
                var data = convert.ephemeris2vector(object.ephemeris);
                object.position= data.position;
                object.velocity= data.velocity;
            }
            
            var lua_data = lua.object2lua(object);
            console.log(lua_data);
            fs.writeFile(object.name + ".lua", lua_data); 
        });
    }
}



